# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/movie_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=sairam

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

omdb.api.key=e609cf71

watchmode.api.key=UqBYB3UzXHzI35szBnP5duRGVdDxAbijWIEPqnZn